name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Plugin
        run: |
          cd MinecraftUHC && \
          chmod +x gradlew && \
          ./gradlew shadowJar && \
          cd ..

      - name: Download papermc
        run: curl -LJ https://api.papermc.io/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar -o template/paper.jar

      - uses: feavy/deploy@main
        env:
          DOCKERFILE_PATH: .
          DOCKER_IMAGE: mc-uhc:latest
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          GITHUB_USERNAME: feavy
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DEPLOYMENT: deployment.yml
          MINECRAFT_TOKEN: "${{ secrets.MINECRAFT_TOKEN }}"
          MINECRAFT_CHANNEL: "427561263485419531"
          PLATFORM: arm64

      - name: Restart deployment
        run: kubectl rollout restart deployment mc-uhc --namespace feavy
